# Generated by Django 4.0.5 on 2022-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0003_pat_ap_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pat_ap',
            name='doc_name',
            field=models.CharField(max_length=30),
        ),
    ]
