# Generated by Django 3.1 on 2022-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0004_alter_pat_ap_doc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('pat_name', models.CharField(max_length=30)),
                ('doc_name', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='docs/')),
            ],
        ),
    ]
